const DONOR = "DONOR";
const SPONSOR = "SPONSOR";
const VOLUNTEER = "VOLUNTEER";
const ADMIN = "ADMIN";
const ORPHANAGE_ADMIN = "ORPHANAGE ADMIN";

module.exports = {
    DONOR,
    SPONSOR,
    VOLUNTEER,
    ADMIN,
    ORPHANAGE_ADMIN
}
