const DONOR = "DONOR";
const SPONSOR = "SPONSOR";
const VOLUNTEER = "VOLUNTEER";
const ADMIN = "ADMIN";
const ORPHANAGE_ADMIN = "ORPHANAGE ADMIN";
const DRIVER = "DRIVER";
const SUPPORT_PROGRAM_ADMIN="SUPPORT PROGRAM ADMIN";
module.exports = {
    DONOR,
    SPONSOR,
    VOLUNTEER,
    ADMIN,
    ORPHANAGE_ADMIN,
    DRIVER,
    SUPPORT_PROGRAM_ADMIN
}
